//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.19 at 06:24:00 PM EEST 
//


package org.senro.ui.template.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="DisplayGroup" type="{http://www.siveco.ro/senro/DesignerComponent}DisplayGroupType"/>
 *           &lt;element name="EditingContext" type="{http://www.siveco.ro/senro/DesignerComponent}EditingContextType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "displayGroupOrEditingContext"
})
@XmlRootElement(name = "Client")
public class Client {

    @XmlElements({
        @XmlElement(name = "DisplayGroup", type = DisplayGroupType.class),
        @XmlElement(name = "EditingContext", type = EditingContextType.class)
    })
    protected List<BasicComponentType> displayGroupOrEditingContext;

    /**
     * Gets the value of the displayGroupOrEditingContext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayGroupOrEditingContext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayGroupOrEditingContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayGroupType }
     * {@link EditingContextType }
     * 
     * 
     */
    public List<BasicComponentType> getDisplayGroupOrEditingContext() {
        if (displayGroupOrEditingContext == null) {
            displayGroupOrEditingContext = new ArrayList<BasicComponentType>();
        }
        return this.displayGroupOrEditingContext;
    }

}
