//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.19 at 06:24:00 PM EEST 
//


package org.senro.ui.template.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Label"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}TextField"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}TextArea"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}DateField"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}ComboBox"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}CheckBox"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Button"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Grid"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Template"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Iterator"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Conditional"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Tree"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentChoiceType", propOrder = {
    "labelOrTextFieldOrTextArea"
})
@XmlSeeAlso({
    TreeNodeType.class,
    ElseType.class,
    IfType.class
})
public class ComponentChoiceType {

    @XmlElements({
        @XmlElement(name = "Template", type = TemplateType.class),
        @XmlElement(name = "Tree", type = TreeType.class),
        @XmlElement(name = "CheckBox", type = CheckBoxType.class),
        @XmlElement(name = "Label", type = LabelType.class),
        @XmlElement(name = "TextArea", type = TextAreaType.class),
        @XmlElement(name = "TextField", type = TextFieldType.class),
        @XmlElement(name = "Button", type = ButtonType.class),
        @XmlElement(name = "DateField", type = DateFieldType.class),
        @XmlElement(name = "Conditional", type = ConditionalType.class),
        @XmlElement(name = "Grid", type = GridType.class),
        @XmlElement(name = "Iterator", type = IteratorType.class),
        @XmlElement(name = "ComboBox", type = ComboBoxType.class)
    })
    protected List<UIComponentType> labelOrTextFieldOrTextArea;

    /**
     * Gets the value of the labelOrTextFieldOrTextArea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelOrTextFieldOrTextArea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelOrTextFieldOrTextArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemplateType }
     * {@link TreeType }
     * {@link CheckBoxType }
     * {@link LabelType }
     * {@link TextAreaType }
     * {@link TextFieldType }
     * {@link ButtonType }
     * {@link DateFieldType }
     * {@link ConditionalType }
     * {@link GridType }
     * {@link IteratorType }
     * {@link ComboBoxType }
     * 
     * 
     */
    public List<UIComponentType> getLabelOrTextFieldOrTextArea() {
        if (labelOrTextFieldOrTextArea == null) {
            labelOrTextFieldOrTextArea = new ArrayList<UIComponentType>();
        }
        return this.labelOrTextFieldOrTextArea;
    }

}
