//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.18 at 11:16:54 AM EET 
//


package org.senro.ui.template.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GridType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GridType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siveco.ro/senro/ComponentTemplate}UIComponentType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Columns"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Rows"/>
 *         &lt;element name="Components">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Label"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}TextField"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}TextArea"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}DateField"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}ComboBox"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}CheckBox"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Button"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Grid"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Template"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Iterator"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Conditional"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Tree"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}RootPanel"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}GridAllocatorRenderer"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}List"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}TabPanel"/>
 *                     &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}SwitchComponent"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GridType", propOrder = {
    "columns",
    "rows",
    "components"
})
@XmlSeeAlso({
    PopupType.class
})
public class GridType
    extends UIComponentType
{

    @XmlElement(name = "Columns", required = true)
    protected Columns columns;
    @XmlElement(name = "Rows", required = true)
    protected Rows rows;
    @XmlElement(name = "Components", required = true)
    protected GridType.Components components;

    /**
     * Gets the value of the columns property.
     * 
     * @return
     *     possible object is
     *     {@link Columns }
     *     
     */
    public Columns getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Columns }
     *     
     */
    public void setColumns(Columns value) {
        this.columns = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link Rows }
     *     
     */
    public Rows getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rows }
     *     
     */
    public void setRows(Rows value) {
        this.rows = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link GridType.Components }
     *     
     */
    public GridType.Components getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link GridType.Components }
     *     
     */
    public void setComponents(GridType.Components value) {
        this.components = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Label"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}TextField"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}TextArea"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}DateField"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}ComboBox"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}CheckBox"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Button"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Grid"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Template"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Iterator"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Conditional"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Tree"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}RootPanel"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}GridAllocatorRenderer"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}List"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}TabPanel"/>
     *           &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}SwitchComponent"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "labelOrTextFieldOrTextArea"
    })
    public static class Components {

        @XmlElements({
            @XmlElement(name = "TabPanel", type = TabPanelType.class),
            @XmlElement(name = "DateField", type = DateFieldType.class),
            @XmlElement(name = "Button", type = ButtonType.class),
            @XmlElement(name = "CheckBox", type = CheckBoxType.class),
            @XmlElement(name = "GridAllocatorRenderer", type = GridAllocatorRendererType.class),
            @XmlElement(name = "Conditional", type = ConditionalType.class),
            @XmlElement(name = "List", type = ListType.class),
            @XmlElement(name = "Template", type = TemplateType.class),
            @XmlElement(name = "Label", type = LabelType.class),
            @XmlElement(name = "Iterator", type = IteratorType.class),
            @XmlElement(name = "Grid", type = GridType.class),
            @XmlElement(name = "TextArea", type = TextAreaType.class),
            @XmlElement(name = "ComboBox", type = ComboBoxType.class),
            @XmlElement(name = "SwitchComponent", type = SwitchComponentType.class),
            @XmlElement(name = "RootPanel", type = RootPanelType.class),
            @XmlElement(name = "TextField", type = TextFieldType.class),
            @XmlElement(name = "Tree", type = TreeType.class)
        })
        protected List<UIComponentType> labelOrTextFieldOrTextArea;

        /**
         * Gets the value of the labelOrTextFieldOrTextArea property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the labelOrTextFieldOrTextArea property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLabelOrTextFieldOrTextArea().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TabPanelType }
         * {@link DateFieldType }
         * {@link ButtonType }
         * {@link CheckBoxType }
         * {@link GridAllocatorRendererType }
         * {@link ConditionalType }
         * {@link ListType }
         * {@link TemplateType }
         * {@link LabelType }
         * {@link IteratorType }
         * {@link GridType }
         * {@link TextAreaType }
         * {@link ComboBoxType }
         * {@link SwitchComponentType }
         * {@link RootPanelType }
         * {@link TextFieldType }
         * {@link TreeType }
         * 
         * 
         */
        public List<UIComponentType> getLabelOrTextFieldOrTextArea() {
            if (labelOrTextFieldOrTextArea == null) {
                labelOrTextFieldOrTextArea = new ArrayList<UIComponentType>();
            }
            return this.labelOrTextFieldOrTextArea;
        }

    }

}
