//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.19 at 06:24:00 PM EEST 
//


package org.senro.ui.template.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IteratorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IteratorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siveco.ro/senro/DesignerComponent}UIComponentType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Label"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}TextField"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}TextArea"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}DateField"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}ComboBox"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}CheckBox"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Button"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Grid"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Template"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Iterator"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Conditional"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Tree"/>
 *           &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}TreeNode"/>
 *         &lt;/choice>
 *         &lt;element name="CurrentItem" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="list" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IteratorType", propOrder = {
    "labelOrTextFieldOrTextArea",
    "currentItem"
})
public class IteratorType
    extends UIComponentType
{

    @XmlElements({
        @XmlElement(name = "Label", type = LabelType.class),
        @XmlElement(name = "Conditional", type = ConditionalType.class),
        @XmlElement(name = "Grid", type = GridType.class),
        @XmlElement(name = "CheckBox", type = CheckBoxType.class),
        @XmlElement(name = "TextArea", type = TextAreaType.class),
        @XmlElement(name = "Button", type = ButtonType.class),
        @XmlElement(name = "Template", type = TemplateType.class),
        @XmlElement(name = "ComboBox", type = ComboBoxType.class),
        @XmlElement(name = "TreeNode", type = TreeNodeType.class),
        @XmlElement(name = "Iterator", type = IteratorType.class),
        @XmlElement(name = "DateField", type = DateFieldType.class),
        @XmlElement(name = "Tree", type = TreeType.class),
        @XmlElement(name = "TextField", type = TextFieldType.class)
    })
    protected List<Object> labelOrTextFieldOrTextArea;
    @XmlElement(name = "CurrentItem")
    protected Object currentItem;
    @XmlAttribute(required = true)
    protected String list;

    /**
     * Gets the value of the labelOrTextFieldOrTextArea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelOrTextFieldOrTextArea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelOrTextFieldOrTextArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelType }
     * {@link ConditionalType }
     * {@link GridType }
     * {@link CheckBoxType }
     * {@link TextAreaType }
     * {@link ButtonType }
     * {@link TemplateType }
     * {@link ComboBoxType }
     * {@link TreeNodeType }
     * {@link IteratorType }
     * {@link DateFieldType }
     * {@link TreeType }
     * {@link TextFieldType }
     * 
     * 
     */
    public List<Object> getLabelOrTextFieldOrTextArea() {
        if (labelOrTextFieldOrTextArea == null) {
            labelOrTextFieldOrTextArea = new ArrayList<Object>();
        }
        return this.labelOrTextFieldOrTextArea;
    }

    /**
     * Gets the value of the currentItem property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCurrentItem() {
        return currentItem;
    }

    /**
     * Sets the value of the currentItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCurrentItem(Object value) {
        this.currentItem = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setList(String value) {
        this.list = value;
    }

}
