//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.18 at 11:16:54 AM EET 
//


package org.senro.ui.template.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TabPanelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TabPanelType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siveco.ro/senro/ComponentTemplate}UIComponentType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}TabPage" minOccurs="0"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/ComponentTemplate}Iterator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TabPanelType", propOrder = {
    "tabPageAndIterator"
})
public class TabPanelType
    extends UIComponentType
{

    @XmlElements({
        @XmlElement(name = "Iterator", type = IteratorType.class),
        @XmlElement(name = "TabPage", type = TabPageType.class)
    })
    protected List<UIComponentType> tabPageAndIterator;

    /**
     * Gets the value of the tabPageAndIterator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tabPageAndIterator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTabPageAndIterator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IteratorType }
     * {@link TabPageType }
     * 
     * 
     */
    public List<UIComponentType> getTabPageAndIterator() {
        if (tabPageAndIterator == null) {
            tabPageAndIterator = new ArrayList<UIComponentType>();
        }
        return this.tabPageAndIterator;
    }

}
