//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.19 at 06:24:00 PM EEST 
//


package org.senro.ui.template.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TreeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TreeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siveco.ro/senro/DesignerComponent}UIComponentType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}TreeNode" minOccurs="0"/>
 *         &lt;element ref="{http://www.siveco.ro/senro/DesignerComponent}Iterator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TreeType", propOrder = {
    "treeNodeAndIterator"
})
public class TreeType
    extends UIComponentType
{

    @XmlElements({
        @XmlElement(name = "TreeNode", type = TreeNodeType.class),
        @XmlElement(name = "Iterator", type = IteratorType.class)
    })
    protected List<Object> treeNodeAndIterator;

    /**
     * Gets the value of the treeNodeAndIterator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the treeNodeAndIterator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTreeNodeAndIterator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TreeNodeType }
     * {@link IteratorType }
     * 
     * 
     */
    public List<Object> getTreeNodeAndIterator() {
        if (treeNodeAndIterator == null) {
            treeNodeAndIterator = new ArrayList<Object>();
        }
        return this.treeNodeAndIterator;
    }

}
