//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.18 at 11:16:54 AM EET 
//


package org.senro.ui.template.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIComponentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siveco.ro/senro/ComponentTemplate}BasicComponentType">
 *       &lt;attribute name="row" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="col" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="rowSpan" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="colSpan" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="halign" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valign" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIComponentType")
@XmlSeeAlso({
    ConditionalType.class,
    IteratorType.class,
    TabPanelType.class,
    TextAreaType.class,
    ButtonType.class,
    ComboBoxType.class,
    DateFieldType.class,
    TreeType.class,
    GridType.class,
    GridAllocatorRendererType.class,
    CheckBoxType.class,
    ListType.class,
    TemplateType.class,
    TextFieldType.class,
    RootPanelType.class,
    SwitchComponentType.class,
    LabelType.class,
    ComponentChoiceType.class
})
public class UIComponentType
    extends BasicComponentType
{

    @XmlAttribute
    protected String row;
    @XmlAttribute
    protected String col;
    @XmlAttribute
    protected String rowSpan;
    @XmlAttribute
    protected String colSpan;
    @XmlAttribute
    protected String halign;
    @XmlAttribute
    protected String valign;

    /**
     * Gets the value of the row property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRow() {
        if (row == null) {
            return "0";
        } else {
            return row;
        }
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRow(String value) {
        this.row = value;
    }

    /**
     * Gets the value of the col property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCol() {
        if (col == null) {
            return "0";
        } else {
            return col;
        }
    }

    /**
     * Sets the value of the col property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCol(String value) {
        this.col = value;
    }

    /**
     * Gets the value of the rowSpan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowSpan() {
        if (rowSpan == null) {
            return "1";
        } else {
            return rowSpan;
        }
    }

    /**
     * Sets the value of the rowSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowSpan(String value) {
        this.rowSpan = value;
    }

    /**
     * Gets the value of the colSpan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColSpan() {
        if (colSpan == null) {
            return "1";
        } else {
            return colSpan;
        }
    }

    /**
     * Sets the value of the colSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColSpan(String value) {
        this.colSpan = value;
    }

    /**
     * Gets the value of the halign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHalign() {
        return halign;
    }

    /**
     * Sets the value of the halign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHalign(String value) {
        this.halign = value;
    }

    /**
     * Gets the value of the valign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValign() {
        return valign;
    }

    /**
     * Sets the value of the valign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValign(String value) {
        this.valign = value;
    }

}
