//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.19 at 06:24:00 PM EEST 
//


package org.senro.ui.template.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIComponentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siveco.ro/senro/DesignerComponent}BasicComponentType">
 *       &lt;attribute name="row" type="{http://www.siveco.ro/senro/DesignerComponent}positiveInteger" default="0" />
 *       &lt;attribute name="col" type="{http://www.siveco.ro/senro/DesignerComponent}positiveInteger" default="0" />
 *       &lt;attribute name="rowSpan" type="{http://www.siveco.ro/senro/DesignerComponent}strictPositiveInteger" default="1" />
 *       &lt;attribute name="colSpan" type="{http://www.siveco.ro/senro/DesignerComponent}strictPositiveInteger" default="1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIComponentType")
@XmlSeeAlso({
    ConditionalType.class,
    IteratorType.class,
    TemplateType.class,
    TextAreaType.class,
    TextFieldType.class,
    RootPanelType.class,
    GridType.class,
    ButtonType.class,
    ComboBoxType.class,
    TreeType.class,
    DateFieldType.class,
    CheckBoxType.class,
    LabelType.class
})
public class UIComponentType
    extends BasicComponentType
{

    @XmlAttribute
    protected BigInteger row;
    @XmlAttribute
    protected BigInteger col;
    @XmlAttribute
    protected BigInteger rowSpan;
    @XmlAttribute
    protected BigInteger colSpan;

    /**
     * Gets the value of the row property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRow() {
        if (row == null) {
            return new BigInteger("0");
        } else {
            return row;
        }
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRow(BigInteger value) {
        this.row = value;
    }

    /**
     * Gets the value of the col property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCol() {
        if (col == null) {
            return new BigInteger("0");
        } else {
            return col;
        }
    }

    /**
     * Sets the value of the col property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCol(BigInteger value) {
        this.col = value;
    }

    /**
     * Gets the value of the rowSpan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRowSpan() {
        if (rowSpan == null) {
            return new BigInteger("1");
        } else {
            return rowSpan;
        }
    }

    /**
     * Sets the value of the rowSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRowSpan(BigInteger value) {
        this.rowSpan = value;
    }

    /**
     * Gets the value of the colSpan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColSpan() {
        if (colSpan == null) {
            return new BigInteger("1");
        } else {
            return colSpan;
        }
    }

    /**
     * Sets the value of the colSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColSpan(BigInteger value) {
        this.colSpan = value;
    }

}
