//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.18 at 11:16:54 AM EET 
//


package org.senro.ui.template.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.senro.ui.template.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TextField_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "TextField");
    private final static QName _TabPage_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "TabPage");
    private final static QName _TextArea_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "TextArea");
    private final static QName _TabPanel_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "TabPanel");
    private final static QName _Template_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "Template");
    private final static QName _Iterator_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "Iterator");
    private final static QName _Conditional_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "Conditional");
    private final static QName _List_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "List");
    private final static QName _Label_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "Label");
    private final static QName _CheckBox_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "CheckBox");
    private final static QName _SwitchComponent_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "SwitchComponent");
    private final static QName _TreeNode_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "TreeNode");
    private final static QName _Grid_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "Grid");
    private final static QName _GridAllocatorRenderer_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "GridAllocatorRenderer");
    private final static QName _DateField_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "DateField");
    private final static QName _Tree_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "Tree");
    private final static QName _ComboBox_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "ComboBox");
    private final static QName _RootPanel_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "RootPanel");
    private final static QName _Button_QNAME = new QName("http://www.siveco.ro/senro/ComponentTemplate", "Button");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.senro.ui.template.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IteratorType }
     * 
     */
    public IteratorType createIteratorType() {
        return new IteratorType();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link TreeType }
     * 
     */
    public TreeType createTreeType() {
        return new TreeType();
    }

    /**
     * Create an instance of {@link EditingContextType }
     * 
     */
    public EditingContextType createEditingContextType() {
        return new EditingContextType();
    }

    /**
     * Create an instance of {@link GridSpecificationElement }
     * 
     */
    public GridSpecificationElement createGridSpecificationElement() {
        return new GridSpecificationElement();
    }

    /**
     * Create an instance of {@link GridSpecificationElement.Size }
     * 
     */
    public GridSpecificationElement.Size createGridSpecificationElementSize() {
        return new GridSpecificationElement.Size();
    }

    /**
     * Create an instance of {@link RootPanelType }
     * 
     */
    public RootPanelType createRootPanelType() {
        return new RootPanelType();
    }

    /**
     * Create an instance of {@link ComboBoxType }
     * 
     */
    public ComboBoxType createComboBoxType() {
        return new ComboBoxType();
    }

    /**
     * Create an instance of {@link GridAllocatorType }
     * 
     */
    public GridAllocatorType createGridAllocatorType() {
        return new GridAllocatorType();
    }

    /**
     * Create an instance of {@link UIComponentType }
     * 
     */
    public UIComponentType createUIComponentType() {
        return new UIComponentType();
    }

    /**
     * Create an instance of {@link BasicComponentType }
     * 
     */
    public BasicComponentType createBasicComponentType() {
        return new BasicComponentType();
    }

    /**
     * Create an instance of {@link DisplayGroupType }
     * 
     */
    public DisplayGroupType createDisplayGroupType() {
        return new DisplayGroupType();
    }

    /**
     * Create an instance of {@link Params }
     * 
     */
    public Params createParams() {
        return new Params();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link ElseType }
     * 
     */
    public ElseType createElseType() {
        return new ElseType();
    }

    /**
     * Create an instance of {@link GridType }
     * 
     */
    public GridType createGridType() {
        return new GridType();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link SwitchComponentType }
     * 
     */
    public SwitchComponentType createSwitchComponentType() {
        return new SwitchComponentType();
    }

    /**
     * Create an instance of {@link ComponentTemplate }
     * 
     */
    public ComponentTemplate createComponentTemplate() {
        return new ComponentTemplate();
    }

    /**
     * Create an instance of {@link GridAllocatorRendererType }
     * 
     */
    public GridAllocatorRendererType createGridAllocatorRendererType() {
        return new GridAllocatorRendererType();
    }

    /**
     * Create an instance of {@link TextAreaType }
     * 
     */
    public TextAreaType createTextAreaType() {
        return new TextAreaType();
    }

    /**
     * Create an instance of {@link TreeNodeType }
     * 
     */
    public TreeNodeType createTreeNodeType() {
        return new TreeNodeType();
    }

    /**
     * Create an instance of {@link ComponentChoiceType }
     * 
     */
    public ComponentChoiceType createComponentChoiceType() {
        return new ComponentChoiceType();
    }

    /**
     * Create an instance of {@link Rows }
     * 
     */
    public Rows createRows() {
        return new Rows();
    }

    /**
     * Create an instance of {@link ConditionalType }
     * 
     */
    public ConditionalType createConditionalType() {
        return new ConditionalType();
    }

    /**
     * Create an instance of {@link TabPageType }
     * 
     */
    public TabPageType createTabPageType() {
        return new TabPageType();
    }

    /**
     * Create an instance of {@link CheckBoxType }
     * 
     */
    public CheckBoxType createCheckBoxType() {
        return new CheckBoxType();
    }

    /**
     * Create an instance of {@link IfType }
     * 
     */
    public IfType createIfType() {
        return new IfType();
    }

    /**
     * Create an instance of {@link DateFieldType }
     * 
     */
    public DateFieldType createDateFieldType() {
        return new DateFieldType();
    }

    /**
     * Create an instance of {@link SenroContextType }
     * 
     */
    public SenroContextType createSenroContextType() {
        return new SenroContextType();
    }

    /**
     * Create an instance of {@link TabPanelType }
     * 
     */
    public TabPanelType createTabPanelType() {
        return new TabPanelType();
    }

    /**
     * Create an instance of {@link ButtonType }
     * 
     */
    public ButtonType createButtonType() {
        return new ButtonType();
    }

    /**
     * Create an instance of {@link TextFieldType }
     * 
     */
    public TextFieldType createTextFieldType() {
        return new TextFieldType();
    }

    /**
     * Create an instance of {@link Columns }
     * 
     */
    public Columns createColumns() {
        return new Columns();
    }

    /**
     * Create an instance of {@link TemplateType.Param }
     * 
     */
    public TemplateType.Param createTemplateTypeParam() {
        return new TemplateType.Param();
    }

    /**
     * Create an instance of {@link Server }
     * 
     */
    public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link Associations }
     * 
     */
    public Associations createAssociations() {
        return new Associations();
    }

    /**
     * Create an instance of {@link GridType.Components }
     * 
     */
    public GridType.Components createGridTypeComponents() {
        return new GridType.Components();
    }

    /**
     * Create an instance of {@link Assoc }
     * 
     */
    public Assoc createAssoc() {
        return new Assoc();
    }

    /**
     * Create an instance of {@link Layout }
     * 
     */
    public Layout createLayout() {
        return new Layout();
    }

    /**
     * Create an instance of {@link PopupType }
     * 
     */
    public PopupType createPopupType() {
        return new PopupType();
    }

    /**
     * Create an instance of {@link Assoc.Binding }
     * 
     */
    public Assoc.Binding createAssocBinding() {
        return new Assoc.Binding();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextFieldType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "TextField")
    public JAXBElement<TextFieldType> createTextField(TextFieldType value) {
        return new JAXBElement<TextFieldType>(_TextField_QNAME, TextFieldType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TabPageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "TabPage")
    public JAXBElement<TabPageType> createTabPage(TabPageType value) {
        return new JAXBElement<TabPageType>(_TabPage_QNAME, TabPageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "TextArea")
    public JAXBElement<TextAreaType> createTextArea(TextAreaType value) {
        return new JAXBElement<TextAreaType>(_TextArea_QNAME, TextAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TabPanelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "TabPanel")
    public JAXBElement<TabPanelType> createTabPanel(TabPanelType value) {
        return new JAXBElement<TabPanelType>(_TabPanel_QNAME, TabPanelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "Template")
    public JAXBElement<TemplateType> createTemplate(TemplateType value) {
        return new JAXBElement<TemplateType>(_Template_QNAME, TemplateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IteratorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "Iterator")
    public JAXBElement<IteratorType> createIterator(IteratorType value) {
        return new JAXBElement<IteratorType>(_Iterator_QNAME, IteratorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "Conditional")
    public JAXBElement<ConditionalType> createConditional(ConditionalType value) {
        return new JAXBElement<ConditionalType>(_Conditional_QNAME, ConditionalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "List")
    public JAXBElement<ListType> createList(ListType value) {
        return new JAXBElement<ListType>(_List_QNAME, ListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LabelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "Label")
    public JAXBElement<LabelType> createLabel(LabelType value) {
        return new JAXBElement<LabelType>(_Label_QNAME, LabelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckBoxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "CheckBox")
    public JAXBElement<CheckBoxType> createCheckBox(CheckBoxType value) {
        return new JAXBElement<CheckBoxType>(_CheckBox_QNAME, CheckBoxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SwitchComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "SwitchComponent")
    public JAXBElement<SwitchComponentType> createSwitchComponent(SwitchComponentType value) {
        return new JAXBElement<SwitchComponentType>(_SwitchComponent_QNAME, SwitchComponentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TreeNodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "TreeNode")
    public JAXBElement<TreeNodeType> createTreeNode(TreeNodeType value) {
        return new JAXBElement<TreeNodeType>(_TreeNode_QNAME, TreeNodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GridType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "Grid")
    public JAXBElement<GridType> createGrid(GridType value) {
        return new JAXBElement<GridType>(_Grid_QNAME, GridType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GridAllocatorRendererType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "GridAllocatorRenderer")
    public JAXBElement<GridAllocatorRendererType> createGridAllocatorRenderer(GridAllocatorRendererType value) {
        return new JAXBElement<GridAllocatorRendererType>(_GridAllocatorRenderer_QNAME, GridAllocatorRendererType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateFieldType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "DateField")
    public JAXBElement<DateFieldType> createDateField(DateFieldType value) {
        return new JAXBElement<DateFieldType>(_DateField_QNAME, DateFieldType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TreeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "Tree")
    public JAXBElement<TreeType> createTree(TreeType value) {
        return new JAXBElement<TreeType>(_Tree_QNAME, TreeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComboBoxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "ComboBox")
    public JAXBElement<ComboBoxType> createComboBox(ComboBoxType value) {
        return new JAXBElement<ComboBoxType>(_ComboBox_QNAME, ComboBoxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootPanelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "RootPanel")
    public JAXBElement<RootPanelType> createRootPanel(RootPanelType value) {
        return new JAXBElement<RootPanelType>(_RootPanel_QNAME, RootPanelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ButtonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.siveco.ro/senro/ComponentTemplate", name = "Button")
    public JAXBElement<ButtonType> createButton(ButtonType value) {
        return new JAXBElement<ButtonType>(_Button_QNAME, ButtonType.class, null, value);
    }

}
