//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.19 at 06:24:00 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.siveco.ro/senro/DesignerComponent", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.senro.ui.template.model;
